start_vm:
  description: Start a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
stop_vm:
  description: Stop a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
reboot_vm:
  description: Reboot a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
shutdown_vm:
  description: Shutdown a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
reset_vm:
  description: Reset a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
pause_vm:
  description: Pause a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
hibernate_vm:
  description: Hibernate a virtual machine in Proxmox. (vm_id and node_name are required)
  fields:
    vm_id:
      description: The ID of the virtual machine.
      example: "101"
    node_name:
      description: The name of the node.
      example: "proxmox_node"
